#!/usr/bin/env python3

import argparse
import os


def main():
    parser = argparse.ArgumentParser(description='Insert words on each selected line in the file')
    parser.add_argument('-s', '--step', type=int, default=0, required=True, help='Step for inserting words')
    parser.add_argument('-w', '--word', type=str, required=True, help='Word to insert')
    parser.add_argument('input_file', type=str, help='Input file path')
    parser.add_argument('output_file', default='result_insert.txt', type=str, help='Path to output file')

    args = parser.parse_args()

    if not os.path.exists(args.input_file):
        print(f'Incorrect file path [{args.input_file}]')
        exit(0)

    with open(args.input_file, 'r') as file:
        lines = file.readlines()

    with open(args.output_file, 'w') as file:
        for i, line in enumerate(lines):
            if (i + 1) % args.step == 0:
                file.write(f"{args.word}\n")
            file.write(line)


if __name__ == "__main__":
    main()
